version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: telros_postres
    ports:
      - "6666:5432"
    environment:
      POSTGRES_DB: telros_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: telros_minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin #минимум 3 символа
      MINIO_ROOT_PASSWORD: password #минимум 8 символов
    volumes:
      - ./data/minio:/data

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    #    image: telros:0.0.1 - если запускать из готового образа
    container_name: telros_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/telros_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin